# -*- coding: utf-8 -*-

from cloudlib.globalx.config import P_CLOUDFS_CA_CRT,P_CLOUDFS_CA_KEY,P_CLOUDFS_HOST,P_CLOUDFS_PORT,\
    P_CONFIG_EXECUTOR_PORT,P_HTTP_TIMEOUT,P_MYSQL_CONNECTION_TIMEOUT,P_MYSQL_HOST,P_MYSQL_PASSWD,\
    P_MYSQL_PORT,P_MYSQL_USER
    
CLOUDFS_HOST = P_CLOUDFS_HOST
CLOUDFS_PORT = P_CLOUDFS_PORT

CLOUDFS_CA_KEY = P_CLOUDFS_CA_KEY
CLOUDFS_CA_CRT = P_CLOUDFS_CA_CRT

HTTP_TIMEOUT = P_HTTP_TIMEOUT

MYSQL_HOST = P_MYSQL_HOST
MYSQL_PORT = P_MYSQL_PORT
MYSQL_USER = P_MYSQL_USER
MYSQL_PASSWD = P_MYSQL_PASSWD
MYSQL_CONNECTION_TIMEOUT = P_MYSQL_CONNECTION_TIMEOUT

CONFIG_EXECUTOR_PORT = P_CONFIG_EXECUTOR_PORT
