# -*- coding: utf-8 -*-

CONF_CONTROLLER_HOST = '192.168.36.3'
CONF_CLOUDFS_PROXY_HOST = '192.168.36.201'
CONF_CLOUDFS_PROXY_PORT = 443


MO_MONITOR_SERVER_HOST = CONF_CONTROLLER_HOST
MO_MONITOR_SERVER_PORT = 7013
MO_HTTP_TIMEOUT = 100

MO_MONITOR_CONNECT_INTERVAL =  10
MO_MONITOR_LOOP_INTERVAL = 30

MO_PSUTIL_CPU_INTERVAL = 2 
MO_PSUTIL_MEM_INTERVAL = 2
MO_PSUTIL_DISK_INTERVAL = 2 
MO_PSUTIL_NET_INTERVAL = 2
MO_PSUTIL_STORAGE_INTERVAL = 30
MO_PSUTIL_PROCESS_INTERVAL = 5
MO_PSUTIL_SERVICE_INTERVAL = 5 

API_CLOUD_PLATFORM_HOST = CONF_CONTROLLER_HOST
API_CLOUD_PLATFORM_PORT = 7012
API_HTTP_TIMEOUT = 100

MI_CLOUD_PLATFORM_HOST = CONF_CONTROLLER_HOST
MI_CLOUD_PLATFORM_PORT = 7012

MI_HTTP_TIMEOUT = 300
MI_DBSYNC_INTERVAL = 5

L_CLOUDFS_HOST = CONF_CLOUDFS_PROXY_HOST
L_CLOUDFS_PORT = CONF_CLOUDFS_PROXY_PORT

L_CLOUDFS_CA_KEY = '/etc/cloud/ca.key.unsecure'
L_CLOUDFS_CA_CRT = '/etc/cloud/ca.crt'

L_HTTP_TIMEOUT = 100

L_HOST_PATH = '/etc/cloud/hostUuid'

P_CLOUDFS_HOST = CONF_CLOUDFS_PROXY_HOST
P_CLOUDFS_PORT = CONF_CLOUDFS_PROXY_PORT

P_CLOUDFS_CA_KEY = '/etc/cloud/ca.key.unsecure'
P_CLOUDFS_CA_CRT = '/etc/cloud/ca.crt'

P_HTTP_TIMEOUT = 100

P_MYSQL_HOST = CONF_CONTROLLER_HOST
P_MYSQL_PORT = 3306
P_MYSQL_USER = 'root'
P_MYSQL_PASSWD = '111111'
P_MYSQL_CONNECTION_TIMEOUT = 24*60*60

P_CONFIG_EXECUTOR_PORT = 7015

EX_PROXY_CONF_PATH = '/etc/swift/proxy-server.conf'
EX_ACCOUNT_CONF_PATH = '/etc/swift/account-server/1.conf'
EX_CONTAINER_CONF_PATH = '/etc/swift/container-server/1.conf'
EX_OBJECT_CONF_PATH = '/etc/swift/object-server/1.conf'

EX_OPTION_STORAGE_DEVICES = ''
EX_OPTION_OAUTH_HOST = 'auth_oauth_host'
EX_OPTION_OAUTH_PORT = 'auth_oauth_port'