# -*- coding: utf-8 -*-

from cloudlib.globalx.config import L_CLOUDFS_CA_CRT,L_CLOUDFS_CA_KEY,L_CLOUDFS_HOST,L_CLOUDFS_PORT,\
    L_HOST_PATH,L_HTTP_TIMEOUT
    
CLOUDFS_HOST = L_CLOUDFS_HOST
CLOUDFS_PORT = L_CLOUDFS_PORT

CLOUDFS_CA_KEY = L_CLOUDFS_CA_KEY
CLOUDFS_CA_CRT = L_CLOUDFS_CA_CRT

HTTP_TIMEOUT = L_HTTP_TIMEOUT

HOST_PATH = L_HOST_PATH