# -*- coding: utf-8 -*-

from cloudlib.globalx.config import API_CLOUD_PLATFORM_HOST,API_CLOUD_PLATFORM_PORT,API_HTTP_TIMEOUT

CLOUD_PLATFORM_HOST = API_CLOUD_PLATFORM_HOST
CLOUD_PLATFORM_PORT = API_CLOUD_PLATFORM_PORT

HTTP_TIMEOUT = API_HTTP_TIMEOUT
