# -*- coding: utf-8 -*-

from cloudlib.globalx.config import MI_CLOUD_PLATFORM_HOST,MI_CLOUD_PLATFORM_PORT,MI_DBSYNC_INTERVAL,MI_HTTP_TIMEOUT

CLOUD_PLATFORM_HOST = MI_CLOUD_PLATFORM_HOST
CLOUD_PLATFORM_PORT = MI_CLOUD_PLATFORM_PORT

HTTP_TIMEOUT = MI_DBSYNC_INTERVAL
DBSYNC_INTERVAL = MI_HTTP_TIMEOUT

